# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            FOAM@PT
tagline:          'Grupo português de utilizadores da tecnologia OpenFOAM'
description:      'Página de coordenação do primeiro encontro de utilizadores de CFD e da tecnologia OpenFOAM&reg; em Portugal.'
url:              foam-at-pt.github.io
baseurl:          /

author:
  name:           'Administrador do grupo'
  url:            http://foam-at-pt.github.io
  emaila:         foam.at.pt
  emailb:         gmail.com
  

paginate:         5

# Custom vars
github:
  repo:           https://github.com/foam-at-pt/foam-at-pt.github.io
